// ./BODYLOCK
export const LOCK_BODY = 'LOCK_BODY';
export const UNLOCK_BODY = 'UNLOCK_BODY';

// ./UPDATE SCREEN SIZE
export const UPDATE_SCREEN_SIZE = 'UPDATE_SCREEN_SIZE';

// ./CONTENT
export const RECEIVE_CONTENT_LIST = 'RECEIVE_CONTENT_LIST';
export const REQUESTING_CONTENT_LIST = 'REQUESTING_CONTENT_LIST';

// ./CHANNELS
export const RECEIVE_CHANNELS_LIST = 'RECEIVE_CHANNELS_LIST';
export const REQUESTING_CHANNELS_LIST = 'REQUESTING_CHANNELS_LIST';

// ./CREATIVE_SHOWCASE_CATEGORIES
export const REQUESTING_CREATIVE_SHOWCASE_CATEGORIES = 'REQUESTING_CREATIVE_SHOWCASE_CATEGORIES';
export const RECEIVED_CREATIVE_SHOWCASE_CATEGORIES = 'RECEIVED_CREATIVE_SHOWCASE_CATEGORIES';

// ./CATEGORIES
export const RECEIVE_CATEGORIES_LIST = 'RECEIVE_CATEGORIES_LIST';
export const REQUESTING_CATEGORIES_LIST = 'REQUESTING_CATEGORIES_LIST';

// ./BUSINESS_UNITS
export const REQUESTING_BUSINESS_UNITS_LIST = 'REQUESTING_BUSINESS_UNITS_LIST';
export const RECEIVE_BUSINESS_UNITS_LIST = 'RECEIVE_BUSINESS_UNITS_LIST';

// ./FILTERS
export const UPDATE_FILTER = 'UPDATE_FILTER';

// ./NAVIGATION
export const OPEN_NAVIGATION = 'OPEN_NAVIGATION';
export const CLOSE_NAVIGATION = 'CLOSE_NAVIGATION';

// ./AGENDA
export const RECEIVE_AGENDA = 'RECEIVE_AGENDA';
export const REQUESTING_AGENDA = 'REQUESTING_AGENDA';

// ./FILTER_MAPS
export const RESET_MAP_FILTERS = 'RESET_MAP_FILTERS';
export const SET_MAP_FILTERS = 'SET_MAP_FILTERS';

// REHYDRATE
export const REHYDRATE = 'persist/REHYDRATE';

// ./HOMEPAGE
export const REQUESTING_HOMEPAGE = 'REQUESTING_HOMEPAGE';
export const RECEIVED_HOMEPAGE = 'RECEIVED_HOMEPAGE';

// ./TAGS
export const REQUESTING_TAGS = 'REQUESTING_TAGS';
export const RECEIVED_TAGS = 'RECEIVED_TAGS';